services:

  frontend:
    build: ./frontend/
    ports:
    - 8888:3333
    environment:
      HTTP_PORT: 3333
      DB_NAME: weather_stats

    depends_on: [ "mongodb" ]

  backend:
    build: ./backend/
    environment:
      DB_NAME: weather_stats
      UPDATE_INTERVAL: 3600
      WEATHER_LOCATION: 46835
    depends_on: [ "mongodb" ]

  mongodb:
    image: mongo:latest
    volumes:
    - mongo:/data/db
    expose: [ 27017 ]

volumes:
  mongo:
